### ISSUE TITLE
Stats factor by time - take 1

### ISSUE THREAD

**Issue by ppapadeas** [mozilla/cardano#2]
We need to display historical numbers for all stats we keep.

For all numbers we should display an absolute number change since last week.
By default there should be an arrow next to the number:
- Green arrow pointing up for positive change
- Red arrow pointing down for negative change

On hover on the arrow you should see a tooltip with absolute change since last week like this:
 `+3 since last week`

**Comment by comzeradd** [comment]
First take completed at dad189c
